
@startuml

!theme cerulean-outline
!include <C4/C4_Container>
!include <c4/C4_Component.puml>


skinparam defaultFontName SansSerif
skinparam defaultFontSize 12
skinparam HyperlinkColor #335DA5
skinparam HyperlinkUnderline false


title \n= Архитектура приложения (монолит)\n


SHOW_PERSON_PORTRAIT()

AddElementTag("users", $bgColor="transparent", $fontColor="#336DA5", $borderThickness="0")
AddElementTag("app", $sprite="react", $shadowing="true", $bgColor="#336DA5", $legendText="host")
AddElementTag("microService", $sprite="java,scale=1", $shadowing="true", $legendText="micro service (eight sided) (no text, no back color)")
AddElementTag("backendContainer", $fontColor=$ELEMENT_FONT_COLOR, $bgColor="#336DA5", $shape=EightSidedShape(), $legendText="backend container (eight sided)")
AddElementTag("storage", $shape=RoundedBoxShape(), $bgColor="lightSkyBlue", $fontColor="black")

Person(admin, "Администратор")
Person(customer, "Клиент", "Пользователи приложения", $sprite="users", $tags="users")


System_Boundary(heating_system, "[[c4_component_mono.puml Smart Home System »»]]") {

    Container(web_app, "Web App", "React JS", "Web App", $tags="app")
    Container(mobile_app, "Mobile App", "React Native", "Mobile UI", $tags="app", $sprite="react", $link="")

    Container(heating_srv, "Heating Manager Service", "java spring", "Heating service", $sprite="spring,scale=0.5", $tags="microService")

    ContainerDb(main_db, "smart-home", "Postgre SQL", "Heating manager\n storage", $sprite="postgresql", $tags="storage")
}

System_Boundary(household_sys, "Households") {
    System_Ext(sensors, "Household\n Sensors")
}


Rel(user, web_app, "uses :443", "https")
Rel(admin, web_app, "uses :443", "https")

Rel(user, mobile_app, "uses :443", "https")
Rel(admin, mobile_app, "uses :443", "https")

Rel(web_app, heating_srv, "requests", "http")
Rel(mobile_app, heating_srv, "requests", "http")

Rel(heating_srv, main_db, "reads/writes :5432", "jdbc")

Rel_R(heating_srv, household_sys, "reads", "RFC")

footer drawn with PlantUML v. %version() and C4-PlantUML v. C4Version()
@enduml
